version: '3.8'

services:
  db:
    container_name: postgres_dev
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: gaiacabinet_dev
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dev-network

volumes:
  db-data:

networks:
  dev-network:
    driver: bridge
